---
- name: copy files to simpli-app
  copy:
    src: "{{ item }}"
    dest: simpli-app
  with_items:
    - .dockerignore
    - Dockerfile
    - app.js
    - package.json

- name: Build Docker image from Dockerfile
  docker_image:
    name: web
    path: simpli-app
    state: build
- name: start simpli container
  docker_container:
    image: web:latest
    path: simpli-app
    name: "simpli-app"
    state: running
    ports:
      - "{{ item[0]}}:{{ item[1] }}"
  with_nested:
    - [3001,3000]
    - [3002,3000]
            
- name: Check if container is running
  shell: docker ps
