---
- name: rebuild Docker image from Dockerfile
  docker_image:
    name: lb
    path: "simpli-lb"
    state: present
    
- name: Rerunning the container1
  docker_container:
    image: lb:latest
    state: restarted
    name: "simpli-lb"
    ports:
     - "8080:80" 
